baseURL = 'https://deft.technology'
languageCode = 'en-us'
title = 'Deft Technology'
theme = 'PaperMod'

[params]
    env = 'production'
    description = 'Practical experiments in low-cost internet infrastructure. My goal is simple: identify tools that are fun to learn at home but powerful enough to solve real-world corporate challenges. No fluff, just functional tech.'
    showShareButtons = true
    showCodeCopyButtons = true

    # Move the social icons ABOVE the homeInfoParams or make sure they are clearly defined
    [[params.socialIcons]]
        name = "email"
        url = "mailto:support@deft.technology"

[params.homeInfoParams]
    Title = "Deft Technology"
    # Using Markdown here makes it much more user friendly!
    Content = """
Practical experiments in low-cost internet infrastructure. My goal is simple: identify tools that are fun to learn at home but powerful enough to solve real-world corporate challenges. No fluff, just functional tech.
"""
