baseURL = 'https://deft.technology'
languageCode = 'en-us'
title = 'Deft Technology'
theme = 'PaperMod'

[params]
    env = 'production'
    description = 'Documenting automation, low-cost SaaS and Cloud setups'
    showShareButtons = true
    showCodeCopyButtons = true
    
    [params.homeInfoParams]
    Title = "Deft Technology"
    Content = "Testing different automation, hosting, and other no to low-cost ways to implement technology."

    [[params.socialIcons]]
        name = "email"
        url = "mailto:support@deft.technology"